services:

  bot_telegram:
    image: ssanchezhlg/bot_telegram_oficial:1.3
    restart: always
    container_name: bot_telegram
    ports: 
      - '8443:8443'
    environment:
      - PORT=8443
      - BOT_TOKEN=1234567890:ABCdefGHIjklMNOpqrsTUVwxyz123456789
      - CHAT_ID=-100987654321
      - EXPECTED_TOKEN=abc123def456ghi789jkl012mno345pqr678
      - proxy_address=                                    
    volumes:
      - '/var/log/telegram-bot:/srv/log'
